[build]
  command = "cd frontend && npm install && npm run build -- --config vue.config.js"
  publish = "frontend/dist"
  port = 3100

[[plugins]]
  package = "netlify-plugin-cache"

[build.environment]
  VUE_APP_API = "http://35.180.226.215:3100"

